const ALPHABET = 'tobeornottobethatisthequestionwhethertisnoblerinthemindtosuffertheslingsandarrowsofoutrageousfortuneortotakearmsagainstaseaoftroublesandbyopposingendthemtodietosleepnomoreandbyasleeptosayweendtheheartacheandthethousandnaturalshocksthatfleshisheirtotisaconsummationdevoutlytobewishdtodietosleeptosleepperchancetodreamaytherestherubforinthatsleepofdeathwhatdreamsmaycomewhenwehaveshuffledoffthismortalcoilmustgiveuspausetherestherespectthatmakescalamityofsolonglifeforwhowouldbearthewhipsandscornsoftimethoppressorswrongtheproudmanscontumelythepangsofdisprizdlovethelawsdelaytheinsolenceofofficeandthespurnsthatpatientmeritofthunworthytakeswhenhehimselfmighthisquietusmakewithabarebodkinwhowouldfardelsbeartogruntandsweatunderawearylifebutthatthedreadofsomethingafterdeaththeundiscoveredcountryfromwhosebournnotravellerreturnspuzzlesthewillandmakesusratherbearthoseillswehavethanflytoothersthatweknownotofthusconsciencedothmakecowardsofusallandthusthenativehueofresolutionissickliedoerwiththepalecastofthoughtandenterprisesofgreatpithandmomentwiththisregardtheircurrentsturnawryandlosethenameofaction'

let index = 0

export default function Letter (): string {
  const letter = ALPHABET[index]

  index = (index + 1) % ALPHABET.length

  return letter
}
